coderxio/sagerx

airflow/dags/rxclass/rxclass_atc_to_product_dag.py, airflow/dags/rxnorm_historical/rxnorm_historical.py, airflow/dags/rxnorm_historical/rxnorm_historical_dag.py, dbt/sagerx/models/intermediate/ndc/int_ndc_all_ndcs_to_sources.sql, dbt/sagerx/models/intermediate/rxnorm/int_rxnorm_all_ndcs_to_product_rxcuis.sql, dbt/sagerx/models/staging/rxnorm/stg_rxnorm__all_ndcs.sql, dbt/sagerx/models/staging/rxnorm/stg_rxnorm__mthspl_ndcs.sql, dbt/sagerx/models/staging/rxnorm_historical/_rxnorm_historical__sources.yml, dbt/sagerx/models/staging/rxnorm_historical/stg_rxnorm_historical__ndcs.sql, docker-compose.yml
Resolves #32 
Resolves #56
Added a DAG for RxNorm Historical and one for RxClass ATC.  Both use the respective APIs to loop through all product-level RXCUIs (TTY = SCD, SBD, GPCK, BPCK) in RxNorm (about 60k+) which takes about 5 hours per DAG to run to completion.  The ATC DAG just gets the ATC code from the JSON response.  The RxNorm Historical DAG saves the entire JSON object and then parses through it with PostgreSQL in a second task.
I also added a first pass at a "main NDC" table that contains NDCs from ALL sources (FDA, RxNorm, etc) and an indicator of which source the NDC came from.
Future work is needed to incrementally add historical NDCs from the RxNorm API with each monthly RxNorm release.  I didn't get to that as part of this PR.
We had considered downloading every single …
=> RxNorm Historical NDCs and RxClass ATCPROD (ATC codes -> Product RXCUIs)

README.md, docker-compose.yml
Update instructions around DBT documentation local hosting. Also open port 8080 (DBT documentation default port) to DBT container. This allows users to serve documentation locally and inspect changes when appropriate.
dbt docs generate then dbt docs serve
1. Attach testing logs inside a summary block:
<details>
<summary>testing logs</summary>
```
```
</details>
=> Update DBT for docs

airflow/dags/rxclass/rxclass_atc_to_product_dag.py
The ATCPROD DAG was limited to 100 for testing purposes.  I removed the LIMIT 100 from the SQL to get RXCUIs.
Also it was missing a "MILESTONE" logging feature which emits a log every 1000 API calls (MILESTONE 1000, MILESTONE 2000, etc)..
Also I commented out the exception printing b/c it was noisy.  Should probably clean this up in the future if exceptions are important.
Wanted it to be useful out of the box - would be confusing if users had to remove the limit themselves.
Currently running the DAG - MILESTONEs are showing up appropriately thus far.
=> ATC to Product - Remove LIMIT 100

airflow/dags/rxnorm/terms-of-service.md
Fixes #67
Added RxNorm terms of service.
UMLS requests per this website -> https://www.nlm.nih.gov/research/umls/rxnorm/docs/termsofservice.html.
Looked at the markdown.
=> Add RxNorm terms of service

README.md
Resolves Undocumented Issue
Switched the docker instructions from `docker-compose` to `docker compose` per updates here: https://stackoverflow.com/questions/66514436/difference-between-docker-compose-and-docker-compose
When running the docker commands per instructions in the root `sagerx` directory, the `docker-compose` commands would fail with an error "no such dockerfile". Dr. Google suggested this solution and it worked.
Ran `docker compose up airflow-init` and it worked
Ran `docker-compose up airflow-init` and it didnt'
=> feat: update readme to reflect docker change

airflow/dags/fda_excluded/dag.py, airflow/dags/fda_unfinished/dag.py
Aligned FDA excluded and unfinished DAGs with the FDA NDC DAG so that they all run daily b/c they are all updated daily.
To make it easier to update NDC Description mart - I don't have to trigger the excluded / unfinished DAGs manually anymore.
Ran DAGs to completion.  Saw that once the change was made, a DAG run happened immediately.
=> Schedule FDA excluded and unfinished DAGs to run daily

.gitignore, dbt/sagerx/models/marts/products/_products__models.yml, dbt/sagerx/models/marts/products/brand_products_with_related_ndcs.sql, dbt/sagerx/models/marts/products/products.sql, dbt/sagerx/models/staging/rxnorm/stg_rxnorm__products.sql
Fixes #278 
Created a staging table to represent all RxNorm products.
Created a mart for product-level information - potentially useful for many applications in the future.
Created a specific mart for Brand Product RXCUI → Related Clinical Product RXCUI → NDCs related to that Clinical Product RXCUI → FDA Start Marketing Dates.
Two marts requested by customer.
Product mart could be used generally for other things.
See documentation here
brand_products_with_related_ndcs
https://dbt.sagerx.io/#!/model/model.sagerx.brand_products_with_related_ndcs
products
https://dbt.sagerx.io/#!/model/model.sagerx.products
=> Two new product-related marts

dbt/sagerx/models/marts/classification/atc_codes_to_rxnorm_products.sql
Add ATC codes (not just names) to classification mart per request.
So codes can be used in analysis.
Ran DAG and viewed results.
=> Add ATC codes to mart

dbt/sagerx/models/intermediate/rxnorm/int_rxnorm_clinical_products_to_ingredients.sql, dbt/sagerx/models/marts/products/_products__models.yml, dbt/sagerx/models/marts/products/brand_products_with_related_ndcs.sql, dbt/sagerx/models/marts/products/products.sql, dbt/sagerx/models/staging/rxnorm/stg_rxnorm__clinical_product_components.sql, dbt/sagerx/models/staging/rxnorm/stg_rxnorm__products.sql
It was identified that there were duplicate rows and not great cross-match between ndc mart and RXCUI product mart.
I found an oversight where I was only including a subset of all product RXCUIs and fixed.
I pipe-delimited " | " product info - mostly (entirely?) GPCK/BPCK products that had multiple products and ingredients within them and sometimes different dose forms, etc.  Need to come up with a better solution to this to maintain granularity, but this will do for now.
Also added a dbt test to ensure product RXCUIs are unique in the products mart.
Customer request - need to maintain granularity of product RXCUI.
Ran dbt build for mart and dependencies.
No duplicate product RXCUIs in products mart.
Joined to ndc table and got 100% match.
=> Fix to new RXCUI product mart

airflow/dags/build_marts/dag.py, airflow/dags/export_marts/dag.py, dbt/sagerx/models/marts/ndc/all_ndcs_to_sources.sql, dbt/sagerx/models/marts/products/products_to_inactive_ingredients.sql
Added all_ndcs_to_sources as a mart and limited it to only NDCs in the existing NDC description mart so the row counts match.
Added a product to inactive ingredient mart which just pulls from the existing mthspl intermediate table.
Added the product marts I've been working on per request from customer.
To make it easier to use as marts when ready.
Ran build_marts and export_marts and checked AWS s3 bucket.
=> Add new marts - excipients, products, and NDC sources

dbt/sagerx/dbt_project.yml
Sets intermediate models to materialize as tables (vs views).
dbt mart models are made up of complex logic that should be captured in the intermediate models. The issues already that we ran into (issue https://github.com/coderxio/sagerx/issues/270 ) was that performing these aggregations for each query took 10+ minutes. Therefore, bringing this aggregation into a separated intermediate model to be materialized as a table is a good solution. The materialization of these intermediate tables can take awhile but will significantly speed up queries.
Additional work can be done to optimize the queries that build out intermediate models in the future.
dbt run --full-refresh
=> Intermediate models as tables

airflow/dags/common_dag_tasks.py, dbt/sagerx/models/staging/fda_excluded/_fda_excluded__models.yml, dbt/sagerx/models/staging/fda_excluded/stg_fda_excluded__classes.sql, dbt/sagerx/models/staging/fda_excluded/stg_fda_excluded__substances.sql, dbt/sagerx/models/staging/fda_ndc/_fda_ndc__models.yml, dbt/sagerx/models/staging/fda_ndc/stg_fda_ndc__classes.sql, dbt/sagerx/models/staging/fda_ndc/stg_fda_ndc__substances.sql, dbt/sagerx/models/staging/fda_unfinished/_fda_unfinished__models.yml, dbt/sagerx/models/staging/fda_unfinished/stg_fda_unfinished__substances.sql
- Cleans up the dbt for some of the FDA DAGs 
- Removes the SELECT * from the SQL which makes it hard to understand what tables are being captured 
- Moves some of the complicated SQL logic into CTEs to make it more understandable and maintainable 
- replaces tests to data_tests as is recommended by dbt now
- adds airflow exception to the transform task capturing errors and incomplete runs
Making the SQL understandable and maintainable is important  
- ran each DAG and then queries a staged table
=> FDA Cleanup

airflow/dags/fda_excluded/load_package.sql, airflow/dags/fda_excluded/load_product.sql, airflow/dags/fda_ndc/load_package.sql, airflow/dags/fda_ndc/load_product.sql, airflow/dags/fda_unfinished/load_package.sql, airflow/dags/fda_unfinished/load_product.sql, airflow/dags/rxnorm_historical/dag_tasks.py, airflow/dags/sagerx.py
@leemlb06pmi and @Komal77rao did this work.
Created indexes for FDA DAGs that just use SQL to load data.
Updated `load_df_to_pg` method in `sagerx.py` to handle creation of indexes for dataframe-based data loads.
Improve performance / efficiency by adding indexes.
=> Create SQL indexes and method for creating df indexes

airflow/dags/sagerx.py
Resolves #314 
Moved the index creation below the df_to_sql call.  Seems to have fixed the bug.
Also removed the distinction between single and multiple columns in the params as join won't add a comma if there's only one item in the list.
This kept erroring out at the very end of my rxnorm_historical runs which take an hour which was very frustrating. I think this fixes it, but not sure if doing it this way introduces other issues.
Ran rxnorm_historical on only BPCK TTYs (to reduce run time).  Errored out like normal without my change. Then I ran it with no existing rxnorm_historical table and it worked and created the index.  Then I ran it again with the rxnorm_historical table existing and it worked and created the index.
=> Fix index bug

airflow/dags/build_marts/dag.py, airflow/dags/common_dag_tasks.py, airflow/dags/nadac/dag.py, airflow/dags/rxnorm/dag.py
Changed the common transform task to handle multiple levels of transformation (staging alone or staging and intermediate). I still need to figure out the best way to handle marts because we use the + character in front of the model - I believe to indicate we want dbt to run all dependent models for these(?).  Either way, I left the build_marts tasks alone for now - hardcoded into the task.
Currently, you can only transform data into staging models because we didn't account for intermediate models. This allows flexibility to do either or both.
Tested running DAGs that only had staging models and also ones that had both staging and intermediate models.
=> Change transform to list

airflow/dags/rxnorm/dag.py
Resolves #ISSUE NUMBER
There was a line left over from a merge in the rxnorm dag.py file that was causing errors. Removed this line
I really wanted things to work :)
Changed, ran DAG without issue, no errors.
1. Attach testing logs inside a summary block:
<details>
<summary>testing logs</summary>
```
```
</details>
=> Remove errant string in rxnorm

airflow/dags/sagerx.py
Sometimes when I run rxnorm_historical I get a SIGKILL error and the DAG runs forever, never stopping. https://github.com/coderxio/sagerx/issues/307
This doesn't fully resolve that issue, but it makes it better for my machine.  
Also added a counter for logging every 1000 responses.
I kept having to do this manually and at least one other person said this fixed the bug for them when they did it manually.
Ran RxNorm Historical.
=> Max workers 3

airflow/dags/build_marts/dag.py
The `build_marts` DAG in Airflow was failing. The log indicated that an error was occuring in the `products_to_inactive_ingredients` model:
> [2025-01-13, 16:31:05 PST] {subprocess.py:93} INFO - [0m00:31:05    Database Error in model products_to_inactive_ingredients (models/marts/products/products_to_inactive_ingredients.sql)
[2025-01-13, 16:31:05 PST] {subprocess.py:93} INFO -   relation "sagerx_dev.usp_preservatives" does not exist
[2025-01-13, 16:31:05 PST] {subprocess.py:93} INFO -   LINE 23:     select * from "sagerx"."sagerx_dev"."usp_preservatives"
I checked, and indeed the `usp_preservatives` table was missing from the database. I saw the `usp_preservatives.csv` file in the seeds directory of the repo, and while the seeds configuration appeared to be correct, I couldn't find `dbt …
=> fix seeding of `usp_preservatives` table

airflow/dags/sagerx.py
Fixes #340 
Per suggestion from @Bridg109 - adding headers to the requests call to FDA data source. He gave me these headers and when I plugged them in, everything was working again.
See notes in #340 for why I had to make this change.
Have been running SageRx for a few weeks on this branch with no issues.
=> Add headers to requests

dbt/sagerx/models/marts/ndc/gtins.sql
Fixes #334 
Created a mart that attempts to translate NDCs to GTINs following some basic understanding of how GTINs can be calculated. Big disclaimer - this is just a proof of concept and is not validated.
Useful for barcode scanning and maybe track and trace related endeavors.
Ran mart to completion
=> Create GTINs mart

airflow/dags/rxclass/dag_tasks.py
"Resolves" #331 
Optimized current dag_tasks file by doing the following:
1. changed the `rxclass_df.append()` from appending a new dataframe with each append to collecting all the created rows in a list and then creating the final dataframe from that list
2. used the pandas deduplication method to remove duplicates that @jrlegrand mentioned in issue 331
3. tried speeding up api requests by making the requests asynchronous while keeping the rate to 20 calls per second
@jrlegrand was able to fix the code so that it runs, but mentioned that the code ran slowly. I was able to confirm this and the adjustments make reduced the time to create `sagerx_lake.rxclass` by more than half
- Did a quick QA by counting the number of rows in the table before and after the …
=> optimize rxclass code

airflow/dags/rxnorm/dag.py
It threw an error. I fixed it. Not sure when this started.
=> Fix typo in RxNorm transform

airflow/dags/ashp/dag.py, dbt/sagerx/models/staging/ashp/_ashp__models.yml, dbt/sagerx/models/staging/ashp/_ashp__sources.yml, dbt/sagerx/models/staging/ashp/stg_ashp__current_drug_shortages_ndcs.sql
Resolves #325
Updated ASHP drug shortages dag to pull more granular information for each NDC listed on the individual shortage pages. Previously, the `stg_ashp__current_drug_shortages_ndcs` view contained only columns for id, NDC-11, and shortage type (affected or available). This update adds columns for the drug product, manufacturer, and package description.
These columns can be used to compare against NDC information from other data sources. This was a specific request from #325.
Testing was performed manually after rebasing with the most recent commit to main. A sample of the first 10 rows of the updated view are provided:
|id|product|manufacturer|description|ndc_11|ndc_type|
|--|-------|------------|-----------|------|--------|
|1127|5% Sodium Chloride| BBraun| 500 mL bag, 24 …
=> Add additional NDC information in ASHP shortages dataset

dbt/sagerx/models/staging/rxnorm/stg_rxnorm__hcpcs_codes.sql
Literally just deleted a semicolon in a staging table SQL file.
Threw an error on all transform tasks.
Tested a broken DAG task before and after and error was resolved with this change.
=> Fix semicolon error in staging table

dbt/sagerx/models/staging/rxclass/_rxclass_models.yml
Resolves #370 
Deleted a duplicate dbt model definition that was causing errors.
Would like @saywurdson to review to make sure there wasn't supposed to be another model definition in place of this duplicate one. I tried looking through the other models and comparing but there's a lot and I didn't look closely if you wanted to review.
Dbt does not allow duplicate model definitions and it was causing errors.  See related issue #370.
I never had this error weirdly, but @eddie-cosma stated it resolved his issue. Also it is just  present in error.
=> Remove duplicate model definition

dbt/sagerx/models/intermediate/fda/int_fda_packaging_components.sql
At one point, the int_fda_packaging_components model required me to multiple an aggregate array and the only way I could do this was with a custom PostgreSQL function. I don't think I ever documented this function (likely from Stackoverflow) and now it's not working. I temporarily replaced the total pack size with a NULL.
This was breaking build_marts.
Need to add back the array_product custom function - hence the creation of #378 to track this work.
=> Nerf pack size mart to temporarily fix build_marts bug

README.md
Resolves #ISSUE NUMBER
[What did you change?]
[Why did you make the changes mentioned above? What alternatives did you consider?]
1. Attach testing logs inside a summary block:
<details>
<summary>testing logs</summary>
```
```
</details>
=> Updated README to include a troubleshooting step

airflow/dags/cms_asp/dag.py, airflow/dags/cms_asp/dag_tasks.py, airflow/dags/cms_hcpcs/dag.py, airflow/dags/cms_hcpcs/dag_tasks.py, airflow/dags/cms_ndc_hcpcs_crosswalk/dag.py, airflow/dags/cms_ndc_hcpcs_crosswalk/dag_tasks.py, airflow/requirements.txt, docker-compose.yml
Resolves #381 
Resolves #382 
Resolves #395 
DAG to pull down CMS ASP + HCPCS + HCPCS to NDC crosswalk.
Unfortunately this data is hosted as Excel in the easiest to use format so we need to include a python package that can extract Excel data. I know it will be useful for other data sources so it's not just a one-off.
Useful for Medicare Part B billing analysis.
Ran DAG to completion.
This requires a version increase of at least Airflow in dockerfile to re-build the container with the python excel package.
=> CMS ASP HCPCS + HCPCS->NDC Crosswalk
